revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    op.create_table(
        "projects",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("business_objective", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(80), server_default="general"),
        sa.Column("status", sa.String(40), server_default="draft"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "datasets",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id"), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("table_name", sa.String(200), nullable=False),
        sa.Column("layer", sa.String(40), server_default="raw"),
        sa.Column("source_type", sa.String(40), server_default="csv"),
        sa.Column("row_count", sa.Integer()),
        sa.Column("column_count", sa.Integer()),
        sa.Column("checksum", sa.String(128)),
        sa.Column("status", sa.String(40), server_default="uploaded"),
        sa.Column("extra_metadata", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "dataset_files",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
        sa.Column("filename", sa.String(500), nullable=False),
        sa.Column("original_filename", sa.String(500), nullable=False),
        sa.Column("mime_type", sa.String(200)),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("encoding", sa.String(40)),
        sa.Column("delimiter", sa.String(8)),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(128)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id"), nullable=False),
        sa.Column("status", sa.String(40), server_default="queued"),
        sa.Column("business_objective", sa.Text(), nullable=False),
        sa.Column("configuration", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("llm_provider", sa.String(40)),
        sa.Column("llm_model", sa.String(120)),
        sa.Column("agent_versions", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.Column("error", sa.Text()),
        sa.Column("current_step", sa.String(80)),
        sa.Column("dataset_versions", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "pipeline_steps",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("name", sa.String(80), nullable=False),
        sa.Column("display_name", sa.String(120), nullable=False),
        sa.Column("status", sa.String(40), server_default="pending"),
        sa.Column("sequence", sa.Integer(), server_default="0"),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.Column("duration_ms", sa.Integer()),
        sa.Column("input_summary", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("output_summary", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("error", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("step_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_steps.id")),
        sa.Column("agent_name", sa.String(80), nullable=False),
        sa.Column("status", sa.String(40), server_default="pending"),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.Column("llm_model", sa.String(120)),
        sa.Column("prompt_tokens", sa.Integer()),
        sa.Column("completion_tokens", sa.Integer()),
        sa.Column("latency_ms", sa.Integer()),
        sa.Column("retry_count", sa.Integer(), server_default="0"),
        sa.Column("input_summary", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("output_summary", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("validation_result", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("error", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "data_profiles",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id")),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("column_count", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float()),
        sa.Column("duplicate_row_count", sa.Integer(), server_default="0"),
        sa.Column("warnings", postgresql.JSONB, server_default=sa.text("'[]'::jsonb")),
        sa.Column("relationships_found", postgresql.JSONB, server_default=sa.text("'[]'::jsonb")),
        sa.Column("pii_flags", postgresql.JSONB, server_default=sa.text("'[]'::jsonb")),
        sa.Column("summary", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "data_profile_columns",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("profile_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("data_profiles.id"), nullable=False),
        sa.Column("name", sa.String(300), nullable=False),
        sa.Column("inferred_type", sa.String(80), nullable=False),
        sa.Column("logical_type", sa.String(80)),
        sa.Column("null_count", sa.Integer(), server_default="0"),
        sa.Column("null_pct", sa.Float(), server_default="0"),
        sa.Column("distinct_count", sa.Integer(), server_default="0"),
        sa.Column("uniqueness_pct", sa.Float(), server_default="0"),
        sa.Column("is_candidate_pk", sa.Boolean(), server_default=sa.false()),
        sa.Column("is_candidate_fk", sa.Boolean(), server_default=sa.false()),
        sa.Column("semantic_hint", sa.String(120)),
        sa.Column("stats", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("warnings", postgresql.JSONB, server_default=sa.text("'[]'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "data_quality_reports",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id")),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("completeness", sa.Float(), nullable=False),
        sa.Column("uniqueness", sa.Float(), nullable=False),
        sa.Column("consistency", sa.Float(), nullable=False),
        sa.Column("validity", sa.Float(), nullable=False),
        sa.Column("referential_integrity", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "data_quality_issues",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("report_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("data_quality_reports.id"), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("issue_type", sa.String(80), nullable=False),
        sa.Column("table_name", sa.String(200)),
        sa.Column("column_name", sa.String(300)),
        sa.Column("rows_affected", sa.Integer(), server_default="0"),
        sa.Column("detection_method", sa.String(120), nullable=False),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column("status", sa.String(40), server_default="open"),
        sa.Column("evidence", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "transformations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("dataset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("datasets.id")),
        sa.Column("table_name", sa.String(200), nullable=False),
        sa.Column("column_name", sa.String(300)),
        sa.Column("operation", sa.String(80), nullable=False),
        sa.Column("rows_affected", sa.Integer(), server_default="0"),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("before_example", sa.Text()),
        sa.Column("after_example", sa.Text()),
        sa.Column("parameters", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("status", sa.String(40), server_default="applied"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "semantic_models",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1"),
        sa.Column("domain", sa.String(80), server_default="general"),
        sa.Column("summary", sa.Text()),
        sa.Column("grain", sa.String(200)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "dimensions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("semantic_model_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("semantic_models.id"), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("table_name", sa.String(200), nullable=False),
        sa.Column("column_name", sa.String(300), nullable=False),
        sa.Column("dim_type", sa.String(40), nullable=False),
        sa.Column("grain", sa.String(80)),
        sa.Column("description", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "measures",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("semantic_model_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("semantic_models.id"), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("table_name", sa.String(200), nullable=False),
        sa.Column("column_name", sa.String(300), nullable=False),
        sa.Column("aggregation", sa.String(40), server_default="SUM"),
        sa.Column("unit", sa.String(40)),
        sa.Column("description", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "relationships",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("semantic_model_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("semantic_models.id"), nullable=False),
        sa.Column("source_table", sa.String(200), nullable=False),
        sa.Column("source_column", sa.String(300), nullable=False),
        sa.Column("target_table", sa.String(200), nullable=False),
        sa.Column("target_column", sa.String(300), nullable=False),
        sa.Column("cardinality", sa.String(40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("validated", sa.Boolean(), server_default=sa.false()),
        sa.Column("overlap_ratio", sa.Float()),
        sa.Column("extra", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "kpis",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("semantic_model_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("semantic_models.id")),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("business_meaning", sa.Text(), nullable=False),
        sa.Column("formula", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(40)),
        sa.Column("dimensions", postgresql.JSONB, server_default=sa.text("'[]'::jsonb")),
        sa.Column("filters", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("data_sources", postgresql.JSONB, server_default=sa.text("'[]'::jsonb")),
        sa.Column("confidence", sa.Float(), server_default="0"),
        sa.Column("validation_status", sa.String(40), server_default="pending"),
        sa.Column("query_sql", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "kpi_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("kpi_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("kpis.id"), nullable=False),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("value", sa.Float()),
        sa.Column("previous_value", sa.Float()),
        sa.Column("change_pct", sa.Float()),
        sa.Column("computed_at", sa.DateTime(timezone=True)),
        sa.Column("query_sql", sa.Text(), nullable=False),
        sa.Column("row_count", sa.Integer()),
        sa.Column("filters", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("breakdown", postgresql.JSONB, server_default=sa.text("'[]'::jsonb")),
        sa.Column("time_series", postgresql.JSONB, server_default=sa.text("'[]'::jsonb")),
        sa.Column("status", sa.String(40), server_default="computed"),
        sa.Column("error", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "analysis_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("analysis_type", sa.String(80), nullable=False),
        sa.Column("metric", sa.String(200), nullable=False),
        sa.Column("details", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("evidence", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "insights",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("kpi_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("kpis.id")),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(80), nullable=False),
        sa.Column("evidence", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("metric", sa.String(200)),
        sa.Column("value", sa.Float()),
        sa.Column("comparison", sa.Text()),
        sa.Column("period", sa.String(120)),
        sa.Column("severity", sa.String(20), server_default="info"),
        sa.Column("confidence", sa.Float(), server_default="0"),
        sa.Column("query_sql", sa.Text()),
        sa.Column("grounded", sa.Boolean(), server_default=sa.true()),
        sa.Column("recommendation", sa.Text()),
        sa.Column("recommendation_basis", sa.String(120)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "dashboard_definitions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id"), nullable=False),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column("layout", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("published", sa.Boolean(), server_default=sa.false()),
        sa.Column("audit_status", sa.String(40), server_default="pending"),
        sa.Column("version", sa.Integer(), server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "dashboard_widgets",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("dashboard_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("dashboard_definitions.id"), nullable=False),
        sa.Column("widget_type", sa.String(40), nullable=False),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column("data_source", sa.String(200)),
        sa.Column("query_sql", sa.Text()),
        sa.Column("kpi_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("kpis.id")),
        sa.Column("dimensions", postgresql.JSONB, server_default=sa.text("'[]'::jsonb")),
        sa.Column("measures", postgresql.JSONB, server_default=sa.text("'[]'::jsonb")),
        sa.Column("filters", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("format", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("position_x", sa.Integer(), server_default="0"),
        sa.Column("position_y", sa.Integer(), server_default="0"),
        sa.Column("width", sa.Integer(), server_default="4"),
        sa.Column("height", sa.Integer(), server_default="2"),
        sa.Column("data", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("explanation", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("event_type", sa.String(80), nullable=False),
        sa.Column("severity", sa.String(20), server_default="info"),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(80)),
        sa.Column("entity_id", sa.String(80)),
        sa.Column("details", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("status", sa.String(40), server_default="recorded"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "xai_explanations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("entity_type", sa.String(80), nullable=False),
        sa.Column("entity_id", sa.String(80), nullable=False),
        sa.Column("what_happened", sa.Text(), nullable=False),
        sa.Column("how_calculated", sa.Text(), nullable=False),
        sa.Column("data_used", sa.Text(), nullable=False),
        sa.Column("visualization_reason", sa.Text()),
        sa.Column("kpi_relevance", sa.Text()),
        sa.Column("assumptions", sa.Text()),
        sa.Column("quality_limitations", sa.Text()),
        sa.Column("transformations", sa.Text()),
        sa.Column("producer_agent", sa.String(80), nullable=False),
        sa.Column("validator_agent", sa.String(80)),
        sa.Column("extra", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "evaluation_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pipeline_runs.id"), nullable=False),
        sa.Column("agent_name", sa.String(80), nullable=False),
        sa.Column("metric_name", sa.String(120), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("details", postgresql.JSONB, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    for table in [
        "evaluation_results",
        "xai_explanations",
        "audit_events",
        "dashboard_widgets",
        "dashboard_definitions",
        "insights",
        "analysis_results",
        "kpi_results",
        "kpis",
        "relationships",
        "measures",
        "dimensions",
        "semantic_models",
        "transformations",
        "data_quality_issues",
        "data_quality_reports",
        "data_profile_columns",
        "data_profiles",
        "agent_runs",
        "pipeline_steps",
        "pipeline_runs",
        "dataset_files",
        "datasets",
        "projects",
    ]:
        op.drop_table(table)
